### ISSUE TITLE
Not compatible with new Google standards - all uploads FAIL!

### ISSUE THREAD

**Issue by vidicunt** [rakeshgirase/app-release-manager#3]
Google changed something in their APIs. No new uploads work anymore.

`Loading account credentials...
Loading file information...
Application Name: communism
Package Name: com.sweettangerine.communism
Loading release notes...
Initialising publisher service...
Initialising new edit...
Edit created. Id: 12337314922374487038
Uploading AAB file...
File uploaded. Version Code: 326
On track:production. Creating a release...
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Track names in request path and request body must match.",
    "reason" : "badRequest"
  } ],
  "message" : "Track names in request path and request body must match.",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1089)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at app.release.publisher.android.AabPublisher.publish(AabPublisher.java:103)
	at app.release.publisher.ApplicationPublisher.main(ApplicationPublisher.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Operation failed due to an error!, Deleting edit...
ERROR: Operation Failed: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Track names in request path and request body must match.",
    "reason" : "badRequest"
  } ],
  "message" : "Track names in request path and request body must match.",
  "status" : "INVALID_ARGUMENT"
}
java.io.IOException: Operation Failed: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Track names in request path and request body must match.",
    "reason" : "badRequest"
  } ],
  "message" : "Track names in request path and request body must match.",
  "status" : "INVALID_ARGUMENT"
}
	at app.release.publisher.android.AabPublisher.publish(AabPublisher.java:126)
	at app.release.publisher.ApplicationPublisher.main(ApplicationPublisher.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Track names in request path and request body must match.",
    "reason" : "badRequest"
  } ],
  "message" : "Track names in request path and request body must match.",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1089)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at app.release.publisher.android.AabPublisher.publish(AabPublisher.java:103)
	... 9 more
`

**Comment by Vladeng** [comment]
+ same problem 
I found it's a mass problem. Hire : [url](https://github.com/r0adkll/upload-google-play/commit/b1260e81f73a4cb9d20c69c2473b2bc279994374#diff-33e4c7efac15c7a2b275b2c223d28a70) how was fixed this problem by another plugin.
